# Generated by Django 5.1.3 on 2024-11-24 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projektWWW', '0002_product_recipe_transaction_recipeproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektWWW.delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projektWWW.product')),
            ],
        ),
    ]
