# Generated by Django 5.1.3 on 2024-11-24 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projektWWW', '0003_deliveryproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='product',
        ),
    ]
